### Health check
GET {{URL}}/health
X-API-Key: {{API_KEY}}

### Generate a new post
POST {{URL}}/post
Content-Type: application/json
X-API-Key: {{API_KEY}}

{
  "category": "cultura"
}

### Update post title and review status
PATCH {{URL}}/post/{{POST_ID}}
Content-Type: application/json
X-API-Key: {{API_KEY}}

{
  "title": "Novo titulo do post",
  "isReviewed": true
}
