@postId = a2dd5327-4094-47a5-8ce4-f46232b92238

### Health check
GET {{URL}}/health
X-PDGN-API-Key: {{PDGN_API_Key}}

### Generate a new post
POST {{URL}}/post
Content-Type: application/json
X-PDGN-API-Key: {{PDGN_API_Key}}

{
  "category": "cultura"
}
