services:
  inngest:
    image: inngest/inngest:v0.27.0
    container_name: newsai_inngest
    command: inngest dev -u http://host.docker.internal:8000/api/inngest --no-discovery
    ports:
      - "8288:8288"
    extra_hosts:
      - "host.docker.internal:host-gateway"
